version: '3'

services:
  db:
    container_name: db
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./datamaster:/data/db
      - ./data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:      
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: 123456  
      MONGO_INITDB_DATABASE: template

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sa
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://sa:123456@db:27017
  
  backend:
      restart: always
      container_name: backend
      build:
          context: .
          dockerfile: Dockerfile
      ports:
          - 5005:3000
      links:
          - db
      depends_on:
          - db